### ISSUE TITLE
Possibility to "Archive" an app

### ISSUE THREAD

**Issue by Dean151** [TelemetryDeck/Viewer#440]
Hi!

This is not an issue, more like a feature request.

It would be tremendous to give the possibility of "Archiving" an app.
Sometime, a project will not come up as we expect, and might be cancelled, or delayed.
Therefore, the only option today to remove it from the main dashboard is to delete it.

I propose an "in-between" state, Archive, that would allow to put the project in a sleep state for the dashboards.

But maybe a dashboard "re-ordering and hiding" would work as well.
Anyway, no rush, just raw ideas dropped on a Sunday morning.

Good luck!

```[tasklist]
### Tasks
- [ ] App Model: add soft deletion
- [ ] App API: Allow filtering by soft deleted
- [ ] App API: Allow "un-deleting" 
- [ ] Web: Allow app archiving and unarchiving 
```
